<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Connexion</title>
</head>
<body>
    <a href="index.php">Accueil</a>
    <a href="inscription.php">Inscription</a>
    <a href="Authentification.php">Connexion</a>
    <form action="" method="post"><br>
        <span>Nom d'utilisateur :</span>
        <input type="text" placeholder="..." name="user">
        <span>Mot de passe :</span>
        <input type="password" placeholder="..." name="password">
        <button>Se connecter</button>
    </form>
</body>

</html>