<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Compte</title>
</head>
<body>
    <a href="index.php">Accueil</a>
    <a href="compte.php">Compte</a>
    <a href="index.php" method="post">Deconnexion</a>
    <h1>ANNONCES</h1>
    <a href="redaction.php">Rédiger une annonce</a>
    <form action="compte.php" method="post">
        <?php foreach ($announcements as $announcement) : ?>
            <li><?= $announcement['title'] ?></li><br>
            <img src="<?= $announcement['image'] ?>"><br><br>
            <?= $announcement['content'] ?><br><br>
            <?= $announcement['publication_date'] ?><br><br>
            <button type="submitt">Modifier</button>
            <a><button type="submitt" href="compte.php">Supprimer</button></a><br><br><br><br>
        <?php endforeach; ?>
    </form>

</body>

</html>