<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="style.css" rel="stylesheet">

    <title>Accueil</title>
</head>
<body>
    <h1>Annonces</h1>
    <a href="index.php">Accueil</a>
    <a href="inscription.php">Inscription</a>
    <a href="Authentification.php">Connexion</a>
    <h3>Annonces</h3>
</body>
</html>