<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier une annonce</title>
</head>

<body>
    <a href="index.php">Accueil</a>
    <a href="compte.php">Compte</a>
    <a href="index.php">Deconnexion</a>
    <h1>Modifier une annonce</h1>
    <form action="update.php" method="post" enctype="multipart/form-data">
        <input type="hidden" name="key" placeholder="Identifiant" value="<?= $_GET['id'] ?>">
        <input type="text" placeholder="Titre" name="title" value="<?= $_GET['id'] ?>">
        <textarea placeholder="Contenu" name="content" id="" cols="30" rows="5" <?= $_GET['id'] ?>></textarea>
        <span>
            <input type="file" name="fichier" accept="image/png, image/jpeg" value="<?= $_GET['id'] ?>">
            <input type="hidden" name="MAX_FILE_SIZE">
        </span>
        <button type="submitt">Publier</button>
    </form>
</body>

</html>